### ISSUE TITLE
Do not allow new payment after payment for registration is completed

### ISSUE THREAD

**Issue by trongtomo** [FPT-Capstone-Group/Smart_Parking_Server#18]

**Comment by Datnqse62453** [comment]
![image](https://github.com/FPT-Capstone-Group/Smart_Parking_Server/assets/44957768/5f6cbcc4-5a6d-4684-89f3-f35617ad6b30)
![image](https://github.com/FPT-Capstone-Group/Smart_Parking_Server/assets/44957768/70a391ab-93ea-4681-bf9c-63c50cb598c8)
submit payment success but  registration.hasPayment do not change

**Comment by Datnqse62453** [comment]
propose 👍 change haspayment = true, update hasPayment in registration  when payemnt success, check hasPayment when call api payments.

**Comment by trongtomo** [comment]
We have removed hasPayment, pls wait for the stable version.

**Comment by trongtomo** [comment]
Add condition before create new payment
```
const registration = await Registration.findByPk(registrationId);
    if (!registration) {
      return errorResponse(req, res, "Registration not found", 404);
    }
    // Registration is already completed, do not allow new payment
    if (registration.registrationStatus === "Active") {
      return errorResponse(req, res, "Registration is already completed", 400);
    }
```
