### ISSUE TITLE
get all card do not response data

### ISSUE THREAD

**Issue by Datnqse62453** [FPT-Capstone-Group/Smart_Parking_Server#20]
![image](https://github.com/FPT-Capstone-Group/Smart_Parking_Server/assets/44957768/88da4621-f22b-4065-9d4a-8d868a608e42)

**Comment by trongtomo** [comment]
@Datnqse62453 
wait for Tuan to release the stable version, and then test.
Before that please restraint your-self from giving me more issue, thanks
![Screenshot 2023-12-02 213258](https://github.com/FPT-Capstone-Group/Smart_Parking_Server/assets/97324726/bc630c41-e2e1-4acd-a1ed-bbba2f1f1670)
